# 2D Numpy in Python

In [1]:
# Import the libraries

import numpy as np

<b>1) Consider the following list <code>a</code>, convert it to Numpy Array. 

In [2]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<b> 2) Calculate the numpy array size.

In [3]:
A.size

12

<b> 3) Access the element on the first row and first and second columns.

In [4]:
# Write your code below and press Shift+Enter to execute
A[0][0:2]

array([1, 2])

<b> 4) Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [5]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

X = np.dot(A,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])