# 1D Numpy in Python

In [1]:
# import numpy library

import numpy as np 

In [2]:
print(np.__version__)

2.2.1


<b> 1) Check the type of the array and Value type for the given array **c**

In [4]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

# Enter your code here
type(b) 


numpy.ndarray

In [5]:
b.dtype 

dtype('float64')

<b> 2) Assign the value 20 for the second element in the given array.

In [6]:
a = np.array([10, 2, 30, 40,50])

# Enter your code here
a[1]=20
a


array([10, 20, 30, 40, 50])

<b> 3) Print the even elements in the given array.

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Enter your code here
print(arr[1:8:2])

[2 4 6 8]


### Assign Value with List


Similarly, we can use a list to select more than one specific index.
The list `select` contains several values:


In [11]:
# Create the index list

select = [0, 2, 3, 4]
c = c = np.array([100, 1, 2, 300, 400])
select

[0, 2, 3, 4]

We can use the list as an argument in the brackets. The output is the elements corresponding to the particular indexes:


In [12]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300, 400])

We can assign the specified elements to a new value. For example, we can assign the values to 100 000 as follows:


In [13]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

<b> 4) Find the size ,dimension and shape for the given array **b**

In [14]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

# Enter your code here
b.size



7

In [15]:
b.ndim


1

In [16]:
b.shape

(7,)

<b> 5) Find the sum of maximum and minimum value in the given numpy array

In [22]:
c = np.array([-10, 201, 43, 94, 502])

# Enter your code here
max_c = c.max() 
min_c = c.min()
Sum = (max_c +min_c)
Sum


np.int64(492)

<b> 6) Implement the following vector subtraction in numpy: u-v

In [23]:
# Write your code below and press Shift+Enter to execute

u = np.array([1, 0])
v = np.array([0, 1])
u - v

array([ 1, -1])

<b> 7) Multiply the numpy array z with -2:


In [24]:
# Write your code below and press Shift+Enter to execute

z = np.array([2, 4])
-2 * z

array([-4, -8])

<b> 8) Consider the list <code>\[1, 2, 3, 4, 5]</code> and <code>\[1, 0, 1, 0, 1]</code>. Cast both lists to a numpy array then multiply them together:


In [25]:
# Write your code below and press Shift+Enter to execute
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])
a * b

array([1, 0, 3, 0, 5])

In [26]:
# Import the libraries

import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt


def Plotvec2(a,b):
    ax = plt.axes()# to generate the full window axes
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)#Add an arrow to the  a Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)#Add an arrow to the  b Axes with arrow head width 0.05, color blue and arrow head length 0.1
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)#set the ylim to bottom(-2), top(2)
    plt.xlim(-2, 2)#set the xlim to left(-2), right(2)
    

ModuleNotFoundError: No module named 'matplotlib'